services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: openai
    networks:
      - message_broker_network
    environment:
      - NODE_ENV=production
      - TZ=Europe/Moscow
    volumes:
      - ./envs:/app/envs
    restart: unless-stopped
volumes:
  rabbitmq_data:
    name: rabbitmq_persistent_data

networks:
  message_broker_network:
    name: rabbitmq_network
    driver: bridge